#!/usr/bin/env node
/**
 * Generates src/content.generated.ts from the repo-root docs — the single
 * source of truth: ../api.md, ../mcp.md, ../templates.md, ../llms.txt.
 *
 * Markdown is converted to HTML at build time and mapped onto the page's
 * design: tables wrapped in <div class="tbl">, HTTP-method badges, section
 * chips, codebox accents, headings demoted one level under the hero <h1>.
 *
 * Run: npm run gen   (also runs automatically via `npm run deploy`).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const workerDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(workerDir, "..");
const read = (name) => readFileSync(join(repoRoot, name), "utf8");

marked.use({ gfm: true });

/** Heading slugs, deduped across ALL sections: two docs may both document
 *  `POST /v1/renders` (one as a pointer, one as the reference), and duplicate
 *  ids would make the deep link land on whichever happened to come first. */
const seenSlugs = new Set();
function uniqueSlug(base) {
  let slug = base;
  for (let n = 2; seenSlugs.has(slug); n++) slug = `${base}-${n}`;
  seenSlugs.add(slug);
  return slug;
}

/** Render one markdown doc into an on-brand HTML section. */
function renderSection(md, { id, pill }) {
  let html = marked.parse(md);
  // Demote headings one level (deepest first) — the page keeps a single hero <h1>.
  html = html
    .replace(/<(\/?)h4>/g, "<$1h5>")
    .replace(/<(\/?)h3>/g, "<$1h4>")
    .replace(/<(\/?)h2>/g, "<$1h3>");
  html = html.replace(/<(\/?)h1>/g, "<$1h2>");
  // The doc title becomes the section heading: anchor id + kit model chip.
  seenSlugs.add(id);
  html = html.replace(/<h2>(.*?)<\/h2>/, `<h2 id="${id}">$1 <span class="chip model">${pill}</span></h2>`);
  // HTTP-method badges on endpoint headings (e.g. "POST /v1/images/generations").
  html = html.replace(/<h3>(GET|POST|PUT|PATCH|DELETE)(?= )/g, '<h3><span class="method">$1</span>');
  // Slug ids on sub-headings, so a deep link like /fonts -> #fonts lands on the
  // right paragraph instead of the top of its section.
  html = html.replace(/<h([34])>((?:<span class="method">\w+<\/span>)?)([\s\S]*?)<\/h\1>/g, (m, lvl, badge, inner) => {
    const slug = inner
      .replace(/<[^>]+>/g, "")
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    return slug ? `<h${lvl} id="${uniqueSlug(slug)}">${badge}${inner}</h${lvl}>` : m;
  });
  // Tables scroll inside the full-bleed wrapper.
  html = html.replace(/<table>/g, '<div class="tbl"><table>').replace(/<\/table>/g, "</table></div>");
  // Kit codebox accents (ui-mockups-v2 .codebox .a/.c): comment lines gray,
  // key placeholders (pf_live_…) beam.
  html = html.replace(/(<pre><code[^>]*>)([\s\S]*?)(<\/code><\/pre>)/g, (_, open, body, close) => {
    const accented = body
      .replace(/^([ \t]*(?:#|\/\/)[^\n]*)$/gm, '<span class="c">$1</span>')
      .replace(/pf_live_[\w…]*/g, '<span class="a">$&</span>');
    return open + accented + close;
  });
  return html.trim();
}

const LLMS = read("llms.txt");
const BODY =
  renderSection(read("api.md"), { id: "api", pill: "REST" }) +
  "\n\n" +
  renderSection(read("templates.md"), { id: "templates", pill: "CARDS" }) +
  "\n\n" +
  renderSection(read("mcp.md"), { id: "mcp", pill: "MCP" });

const out = `/**
 * AUTO-GENERATED by scripts/gen-content.mjs — DO NOT EDIT.
 * Source of truth: api.md, templates.md, mcp.md, llms.txt at the repo root.
 * Regenerate with \`npm run gen\` (runs automatically on deploy).
 */

/** Verbatim contents of /llms.txt. */
export const LLMS = ${JSON.stringify(LLMS)};

/** Rendered HTML body of the docs page (api + templates + mcp sections). */
export const BODY = ${JSON.stringify(BODY)};
`;

writeFileSync(join(workerDir, "src", "content.generated.ts"), out);
console.log("generated src/content.generated.ts");
