#!/usr/bin/env node
/**
 * Generates src/content.generated.ts from the repo-root docs — the single
 * source of truth: ../api.md, ../mcp.md, ../llms.txt.
 *
 * Markdown is converted to HTML at build time and mapped onto the page's
 * design: tables wrapped in <div class="tbl">, HTTP-method badges, section
 * chips, codebox accents, headings demoted one level under the hero <h1>.
 *
 * Run: npm run gen   (also runs automatically via `npm run deploy`).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const workerDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(workerDir, "..");
const read = (name) => readFileSync(join(repoRoot, name), "utf8");

marked.use({ gfm: true });

/** Render one markdown doc into an on-brand HTML section. */
function renderSection(md, { id, pill }) {
  let html = marked.parse(md);
  // Demote headings one level (deepest first) — the page keeps a single hero <h1>.
  html = html
    .replace(/<(\/?)h4>/g, "<$1h5>")
    .replace(/<(\/?)h3>/g, "<$1h4>")
    .replace(/<(\/?)h2>/g, "<$1h3>");
  html = html.replace(/<(\/?)h1>/g, "<$1h2>");
  // The doc title becomes the section heading: anchor id + kit model chip.
  html = html.replace(/<h2>(.*?)<\/h2>/, `<h2 id="${id}">$1 <span class="chip model">${pill}</span></h2>`);
  // HTTP-method badges on endpoint headings (e.g. "POST /v1/images/generations").
  html = html.replace(/<h3>(GET|POST|PUT|PATCH|DELETE)(?= )/g, '<h3><span class="method">$1</span>');
  // Tables scroll inside the full-bleed wrapper.
  html = html.replace(/<table>/g, '<div class="tbl"><table>').replace(/<\/table>/g, "</table></div>");
  // Kit codebox accents (ui-mockups-v2 .codebox .a/.c): comment lines gray,
  // key placeholders (pf_live_…) beam.
  html = html.replace(/(<pre><code[^>]*>)([\s\S]*?)(<\/code><\/pre>)/g, (_, open, body, close) => {
    const accented = body
      .replace(/^([ \t]*(?:#|\/\/)[^\n]*)$/gm, '<span class="c">$1</span>')
      .replace(/pf_live_[\w…]*/g, '<span class="a">$&</span>');
    return open + accented + close;
  });
  return html.trim();
}

const LLMS = read("llms.txt");
const BODY =
  renderSection(read("api.md"), { id: "api", pill: "REST" }) +
  "\n\n" +
  renderSection(read("mcp.md"), { id: "mcp", pill: "MCP" });

const out = `/**
 * AUTO-GENERATED by scripts/gen-content.mjs — DO NOT EDIT.
 * Source of truth: api.md, mcp.md, llms.txt at the repo root.
 * Regenerate with \`npm run gen\` (runs automatically on deploy).
 */

/** Verbatim contents of /llms.txt. */
export const LLMS = ${JSON.stringify(LLMS)};

/** Rendered HTML body of the docs page (api + mcp sections). */
export const BODY = ${JSON.stringify(BODY)};
`;

writeFileSync(join(workerDir, "src", "content.generated.ts"), out);
console.log("generated src/content.generated.ts");
